# Generated by Django 5.1.3 on 2024-11-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_score_project_score_score_type_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('personal_score', models.IntegerField(default=0)),
                ('project', models.CharField(default='', max_length=255)),
                ('role_in_project', models.CharField(default='', max_length=255)),
                ('init', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рейтинг ПД',
                'verbose_name_plural': 'Рейтинг ПД',
                'ordering': ['active'],
            },
        ),
    ]
