# Generated by Django 5.1.3 on 2024-11-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selfmadeprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_score', models.IntegerField(default=0)),
                ('type_project', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Оценка проектов',
                'verbose_name_plural': 'Оценка проектов',
            },
        ),
    ]
