# Generated by Django 5.1.3 on 2024-11-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_selfmadeprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_Self',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('project_score', models.IntegerField(default=0)),
                ('type_project', models.CharField(default='', max_length=200)),
                ('time_project_points', models.IntegerField(default=0)),
                ('crossfunction_points', models.IntegerField(default=0)),
                ('budget_points', models.IntegerField(default=0)),
                ('volume_doc_points', models.IntegerField(default=0)),
                ('scalability_points', models.IntegerField(default=0)),
                ('income_project_ponts', models.IntegerField(default=0)),
                ('tarif_points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Оценка проектов',
                'verbose_name_plural': 'Оценка проектов',
            },
        ),
    ]
